import { useState } from "react";
import { useNavigate, useParams } from "react-router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageHeading } from "@/components/shared/PageHeading";
import { useAuth } from "@/hooks/useAuth";
import { useRoutes } from "@/features/network/hooks/useRoutes";
import { useBays } from "@/features/centres/hooks/useCentres";
import { useDrivers, useVehicles } from "@/features/fleet/hooks";
import { useCreateTrip, useTrip, useUpdateTrip } from "./hooks/useTrips";

export function TripFormPage() {
  const { tripId } = useParams(); const navigate = useNavigate(); const { user } = useAuth();
  const centreId = user?.centreId; const editing = Boolean(tripId);
  const { data: existing, isLoading } = useTrip(tripId); const { data: routes = [] } = useRoutes(centreId);
  const { data: vehicles = [] } = useVehicles({ centreId, status: "Active" }); const { data: drivers = [] } = useDrivers({ centreId, status: "Active" }); const { data: bays = [] } = useBays(centreId);
  const createMutation = useCreateTrip(); const updateMutation = useUpdateTrip(tripId ?? ""); const [error, setError] = useState("");
  if (editing && isLoading) return <main className="p-5">Loading trip...</main>; if (editing && !existing) return <main className="p-5">Trip not found.</main>;
  const scheduled = existing?.scheduledTime ? new Date(existing.scheduledTime) : undefined;
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const data = { centreId: centreId ?? "", routeId: String(form.get("routeId")), vehicleId: String(form.get("vehicleId")), driverId: String(form.get("driverId")), bayId: String(form.get("bayId")), scheduledTime: new Date(`${form.get("date")}T${form.get("time")}`).toISOString(), notes: String(form.get("notes") || "") }; const mutation = editing ? updateMutation : createMutation; mutation.mutate(data, { onSuccess: (result) => navigate(`/operations/dispatch/${editing ? tripId : result?.id}`), onError: (reason) => setError(reason instanceof Error ? reason.message : "Unable to save this trip.") }); };
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-4"><PageHeading title={editing ? "Edit trip" : "Schedule trip"} description="Assign a valid route, time, bay, vehicle, and driver." />{error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<form className="max-w-4xl rounded-lg border bg-card p-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Service date"><Input name="date" type="date" defaultValue={scheduled?.toISOString().slice(0, 10)} required /></Field><Field label="Departure time"><Input name="time" type="time" defaultValue={scheduled?.toTimeString().slice(0, 5)} required /></Field><SelectField label="Route" name="routeId" value={existing?.routeId} options={routes.map((route) => ({ value: route.id, label: `${route.routeNumber} · ${route.name}` }))} /><SelectField label="Bay" name="bayId" value={existing?.bayId} options={bays.filter((bay) => bay.status === "Available").map((bay) => ({ value: bay.id, label: bay.code }))} /><SelectField label="Vehicle" name="vehicleId" value={existing?.vehicleId} options={vehicles.map((vehicle) => ({ value: vehicle.id, label: `${vehicle.plateNumber} · ${vehicle.model}` }))} /><SelectField label="Driver" name="driverId" value={existing?.driverId} options={drivers.map((driver) => ({ value: driver.id, label: `${driver.fullName} · ${driver.licenseNumber}` }))} /><Field label="Operational notes"><Input name="notes" defaultValue={existing?.notes} placeholder="Optional dispatch instructions" /></Field></div><div className="mt-5 rounded-md border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">The API validates centre ownership, readiness, eligibility, bay availability, and scheduling conflicts before saving.</div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => navigate(-1)}>Cancel</Button><Button type="submit" disabled={createMutation.isPending || updateMutation.isPending}>{createMutation.isPending || updateMutation.isPending ? "Saving..." : editing ? "Save trip" : "Schedule trip"}</Button></div></form></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>; }
function SelectField({ label, name, value, options }: { label: string; name: string; value?: string; options: { value: string; label: string }[] }) { return <Field label={label}><Select name={name} defaultValue={value ?? options[0]?.value} required><SelectTrigger className="w-full bg-muted/60"><SelectValue placeholder={`Select ${label.toLowerCase()}`} /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></Field>; }
