import { useState, type ReactNode } from "react";
import { Plus, Search } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageHeading } from "@/components/shared/PageHeading";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { collections } from "@/mock/mock-data";
import { useMockData } from "@/context/MockDataContext";
import { useAuth } from "@/hooks/useAuth";
import { mockRowCentreId } from "@/mock/centre-scope";
import { centres, departuresByCentre } from "@/mock/centres";

export function VehiclesPage({ centreId, basePath = "/fleet/vehicles", readOnly = false }: { centreId?: string; basePath?: string; readOnly?: boolean } = {}) {
  const { data } = useMockData();
  const { user } = useAuth();
  const [query, setQuery] = useState("");
  const effectiveCentreId = centreId ?? user?.centreId;
  const centre = centres.find((item) => item.id === effectiveCentreId);
  const vehicles = data.vehicles ?? collections.vehicles;
  const visibleVehicles = vehicles.filter((vehicle, index) => !effectiveCentreId || mockRowCentreId(vehicle, index) === effectiveCentreId);
  const matchingVehicles = visibleVehicles.filter((vehicle) => `${vehicle.id} ${vehicle.title} ${vehicle.subtitle} ${vehicle.status}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-4"><PageHeading title="Vehicles" description={`${readOnly ? "Read-only fleet assignments, compliance, and service history" : "A fleet workspace for availability, assignments, compliance, and service history"}.`} action={readOnly ? <Button variant="outline" render={<Link to={`/admin/centres/${effectiveCentreId}`} />}>Back to centre</Button> : <Button render={<Link to="/fleet/vehicles/new" />}><Plus /> Register vehicle</Button>} /><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">{matchingVehicles.length} vehicles assigned to {centre?.name ?? "this centre"}</p><div className="relative w-full sm:max-w-xs"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="h-9 bg-card pl-9" placeholder="Search registration or model" /></div></div><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{matchingVehicles.map((vehicle) => <Link key={vehicle.id} to={`${basePath}/${vehicle.id}`} className="group flex rounded-lg border bg-card"><div className="flex w-24 shrink-0 items-center justify-center p-2"><img src="/vehicle-placeholder.svg" alt="UPTS bus placeholder" className="size-20 rounded-md bg-muted object-contain" /></div><div className="flex min-w-0 flex-1 flex-col py-2 pr-3"><div className="flex items-start justify-between gap-2"><p className="font-semibold">{vehicle.id}</p><StatusBadge label={vehicle.status} tone={vehicle.tone} /></div><h2 className="mt-1 text-sm font-medium">{vehicle.title}</h2><p className="mt-2 border-t pt-2 text-xs text-muted-foreground">{vehicle.updated}</p></div></Link>)}{matchingVehicles.length === 0 && <div className="col-span-full rounded-lg border border-dashed bg-card p-8 text-center text-sm text-muted-foreground">No vehicles match this search.</div>}</section></main>;
}

export function VehicleProfilePage({ centreId, basePath = "/fleet/vehicles", readOnly = false }: { centreId?: string; basePath?: string; readOnly?: boolean } = {}) {
  const { data, deactivateRecord } = useMockData();
  const { user } = useAuth();
  const { vehicleId } = useParams();
  const vehicles = data.vehicles ?? collections.vehicles;
  const effectiveCentreId = centreId ?? user?.centreId;
  const scopedVehicles = vehicles.filter((item, index) => !effectiveCentreId || mockRowCentreId(item, index) === effectiveCentreId);
  const vehicle = scopedVehicles.find((item) => item.id === vehicleId) ?? scopedVehicles[0];
  if (!vehicle) return <main className="p-5">Vehicle not found for this centre.</main>;
  const assignment = effectiveCentreId ? departuresByCentre[effectiveCentreId]?.find((item) => item.vehicle === vehicle.id) : undefined;
  const centreName = centres.find((centre) => centre.id === mockRowCentreId(vehicle, vehicles.indexOf(vehicle)))?.name ?? "Not assigned";
  const capacity = vehicle.subtitle.match(/(\d+) seats/)?.[1] ?? "Not recorded";
  const vehicleType = vehicle.subtitle.split(" · ")[0];
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-4"><PageHeading title={vehicle.id} description="Vehicle profile, current operating state, and maintenance readiness." action={readOnly ? <Button variant="outline" render={<Link to={basePath} />}>Back to vehicles</Button> : <div className="flex gap-2"><Button variant="outline" render={<Link to={`/fleet/vehicles/${vehicle.id}/edit`} />}>Edit vehicle</Button><Button variant="destructive" onClick={() => deactivateRecord("vehicles", vehicle.id)}>Deactivate</Button></div>} /><section className="grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(330px,0.9fr)]"><article className="overflow-hidden rounded-lg border bg-card"><img src="/vehicle-placeholder.svg" alt={`Placeholder for ${vehicle.id}`} className="h-64 w-full object-cover" /><div className="grid gap-4 p-5 sm:grid-cols-3"><Info label="Registration" value={vehicle.id} /><Info label="Model" value={vehicle.title} /><Info label="Vehicle type" value={vehicleType} /><Info label="Seat capacity" value={capacity} /><Info label="Accessibility" value={vehicle.subtitle.includes("Accessible") ? "Wheelchair accessible" : "Standard access"} /><Info label="Assigned centre" value={centreName} /><Info label="Operating status" value={vehicle.status} /></div></article><article className="rounded-lg border bg-card p-5"><h2 className="font-semibold">Current assignment</h2><div className="mt-4 rounded-md bg-muted/60 p-4"><p className="text-sm font-medium">{vehicle.updated}</p><p className="mt-1 text-sm text-muted-foreground">{assignment ? `Route ${assignment.route} · ${assignment.destination}` : "No active departure assigned"}</p><p className="mt-3 text-xs text-muted-foreground">{assignment ? `Bay ${assignment.bay} · Departure ${assignment.time} · ${assignment.occupancy}% occupied` : "Vehicle remains available for centre dispatch"}</p></div><h2 className="mt-6 font-semibold">Operational readiness</h2><div className="mt-3 space-y-3"><Meter label="Fuel / charge" value="78%" width="78%" /><Meter label="Inspection compliance" value="Valid" width="100%" /><Meter label="Seat availability" value="9 seats" width="18%" /></div></article></section><section className="grid gap-4 lg:grid-cols-2"><article className="rounded-lg border bg-card p-5"><h2 className="font-semibold">Maintenance timeline</h2><div className="mt-4 space-y-4 border-l pl-4 text-sm"><p><b>Sep 21</b> · Next oil service scheduled</p><p><b>Aug 19</b> · Routine inspection passed</p><p><b>Jul 04</b> · Brake service completed</p></div></article><article className="rounded-lg border bg-card p-5"><h2 className="font-semibold">Service performance</h2><div className="mt-4 grid grid-cols-3 gap-3"><Info label="Trips / 30d" value="184" /><Info label="On-time" value="91.8%" /><Info label="Incidents" value="2" /></div></article></section></main>;
}

export function VehicleFormPage() {
  const { vehicleId } = useParams();
  const navigate = useNavigate();
  const { data, saveRecord } = useMockData();
  const { user } = useAuth();
  const editing = Boolean(vehicleId);
  const existing = data.vehicles?.find((item) => item.id === vehicleId);
  const defaultCentreId = user?.centreId ?? centres[0]?.id;
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-4"><PageHeading title={editing ? `Edit ${vehicleId}` : "Register vehicle"} description="All fields map directly to the Vehicle create and update API request." /><form className="max-w-3xl rounded-lg border bg-card p-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const plateNumber = String(form.get("plateNumber") || vehicleId || "WP-NEW-0001").toUpperCase(); const type = String(form.get("type") || "Normal"); const capacity = Number(form.get("capacity") || 0); const centreId = String(form.get("centreId") || defaultCentreId); saveRecord("vehicles", { id: plateNumber, title: String(form.get("model") || "New vehicle"), subtitle: `${type} · ${capacity} seats · ${form.get("isAccessible") === "on" ? "Accessible" : "Standard"}`, status: String(form.get("status") || "Active"), tone: "neutral", updated: `Centre ${centres.find((centre) => centre.id === centreId)?.name ?? "Unassigned"}`, meta: "Inspection pending", centreId }); navigate(`/fleet/vehicles/${plateNumber}`); }}><div className="grid gap-4 sm:grid-cols-2"><Field name="plateNumber" label="Registration number" value={vehicleId ?? ""} placeholder="WP CAB-4821" /><Field name="model" label="Vehicle model" value={existing?.title} placeholder="Ashok Leyland Viking" /><SelectField name="centreId" label="Assigned centre" defaultValue={defaultCentreId}>{centres.map((centre) => <SelectItem key={centre.id} value={centre.id}>{centre.name}</SelectItem>)}</SelectField><SelectField name="type" label="Vehicle type" defaultValue="Normal"><SelectItem value="Normal">Normal</SelectItem><SelectItem value="SemiLuxury">Semi-luxury</SelectItem><SelectItem value="AcExpress">AC express</SelectItem></SelectField><Field name="capacity" label="Seat capacity" value={existing?.subtitle.match(/(\d+) seats/)?.[1]} placeholder="52" type="number" /><SelectField name="status" label="Operating status" defaultValue="Active"><SelectItem value="Active">Active</SelectItem><SelectItem value="Maintenance">Maintenance</SelectItem><SelectItem value="Inactive">Inactive</SelectItem></SelectField></div><label className="mt-4 flex items-center gap-2 text-sm font-medium"><Checkbox name="isAccessible" defaultChecked={existing?.subtitle.includes("Accessible")} /> Wheelchair accessible</label><p className="mt-3 text-xs text-muted-foreground">Centre, type, capacity, accessibility, and status are required by the fleet API. Current trip assignment is managed in Dispatch, not here.</p><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => navigate(-1)}>Cancel</Button><Button type="submit">{editing ? "Save changes" : "Register vehicle"}</Button></div></form></main>;
}

function Field({ label, value, ...props }: { label: string; name: string; value?: string; placeholder?: string; type?: string }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<Input defaultValue={value} {...props} /></label>; }
function SelectField({ label, name, defaultValue, children }: { label: string; name: string; defaultValue: string; children: ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<Select name={name} defaultValue={defaultValue}><SelectTrigger className="w-full bg-muted/60"><SelectValue /></SelectTrigger><SelectContent>{children}</SelectContent></Select></label>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>; }
function Meter({ label, value, width }: { label: string; value: string; width: string }) { return <div><div className="flex justify-between text-sm"><span>{label}</span><span className="font-medium">{value}</span></div><div className="mt-2 h-1.5 rounded bg-muted"><div className="h-full rounded bg-primary" style={{ width }} /></div></div>; }
