import { Building2, BusFront, ChevronRight, Eye, Plus, Route as RouteIcon, TrainFront, UsersRound } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageHeading } from "@/components/shared/PageHeading";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { useOrganizationMock } from "@/context/OrganizationMockContext";
import type { Centre } from "@/mock/centres";

export function CentresPage() {
  const { centres, employees } = useOrganizationMock();
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-5"><PageHeading title="Multimodal centres" description="Create and govern every terminal in the UPTSLK organization." action={<Button render={<Link to="/admin/centres/new" />}><Plus /> Create centre</Button>} /><section className="overflow-hidden rounded-lg border bg-card"><div className="grid gap-3 border-b px-4 py-3 text-xs font-medium uppercase text-muted-foreground md:grid-cols-[minmax(0,1.2fr)_140px_180px_100px_24px]"><span>Centre</span><span>Status</span><span>Centre manager</span><span>Employees</span><span /></div>{centres.map((centre) => { const centreEmployees = employees.filter((employee) => employee.centreId === centre.id); const manager = centreEmployees.find((employee) => employee.role === "Centre Manager"); return <Link key={centre.id} to={`/admin/centres/${centre.id}`} className="grid gap-3 border-b px-4 py-4 hover:bg-muted/40 md:grid-cols-[minmax(0,1.2fr)_140px_180px_100px_24px] md:items-center"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-md bg-primary/10 text-primary"><Building2 className="size-4" /></div><div><p className="font-medium">{centre.name}</p><p className="text-sm text-muted-foreground">{centre.location} · {centre.bays} bays</p></div></div><StatusBadge label={centre.status} tone={centre.status === "Operating" ? "good" : "neutral"} /><p className="text-sm text-muted-foreground">{manager?.name ?? "Unassigned"}</p><p className="text-sm font-medium">{centreEmployees.length}</p><ChevronRight className="size-4 text-muted-foreground" /></Link>; })}</section></main>;
}

export function CentreProfilePage() {
  const { centreId } = useParams();
  const { centres, employees } = useOrganizationMock();
  const centre = centres.find((item) => item.id === centreId);
  if (!centre) return <main className="p-5">Centre not found.</main>;
  const centreEmployees = employees.filter((employee) => employee.centreId === centre.id);
  const manager = centreEmployees.find((employee) => employee.role === "Centre Manager");
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-5"><PageHeading title={centre.name} description={`${centre.location}, ${centre.district} District`} action={<div className="flex gap-2"><Button variant="outline" render={<Link to={`/admin/centres/${centre.id}/edit`} />}>Edit centre</Button>{centre.status === "Operating" && <Button render={<Link to={`/admin/centres/${centre.id}/operations`} />}><Eye /> View operations</Button>}</div>} /><section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><article className="rounded-lg border bg-card p-5"><div className="flex items-start justify-between"><div className="flex size-11 items-center justify-center rounded-md bg-primary/10 text-primary"><Building2 /></div><StatusBadge label={centre.status} tone={centre.status === "Operating" ? "good" : "neutral"} /></div><h2 className="mt-5 font-semibold">Centre details</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Fact label="Centre code" value={centre.id.toUpperCase()} /><Fact label="District" value={centre.district} /><Fact label="Bus bays" value={String(centre.bays)} /><Fact label="Connected modes" value="Bus · Rail · Taxi · Park & Ride" /><Fact label="Centre manager" value={manager?.name ?? "Not assigned"} /><Fact label="Employees" value={String(centreEmployees.length)} /></div><p className="mt-5 border-t pt-4 text-sm leading-6 text-muted-foreground">{centre.description}</p></article><article className="rounded-lg border bg-card p-5"><h2 className="font-semibold">Governance readiness</h2><div className="mt-4 space-y-3"><Check label="Centre manager assigned" complete={Boolean(manager)} /><Check label="Emergency contacts configured" complete={centre.status === "Operating"} /><Check label="Transport integrations connected" complete={centre.status === "Operating"} /><Check label="Employee roles reviewed" complete={centreEmployees.length > 0} /></div><Button className="mt-5 w-full" variant="outline" render={<Link to={`/admin/employees?centre=${centre.id}`} />}><UsersRound /> Manage employees</Button></article></section><section><h2 className="mb-3 font-semibold">Operational records</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Eye} label="Live operations" value="Bays, departures & seating" href={`/admin/centres/${centre.id}/operations`} /><Summary icon={RouteIcon} label="Routes" value="Service corridors & stops" href={`/admin/centres/${centre.id}/routes`} /><Summary icon={BusFront} label="Fleet" value="Vehicles & readiness" href={`/admin/centres/${centre.id}/vehicles`} /><Summary icon={UsersRound} label="Workforce" value={`${centreEmployees.length} employees`} href={`/admin/employees?centre=${centre.id}`} /></div></section></main>;
}

export function CentreFormPage() {
  const { centreId } = useParams();
  const { centres, saveCentre } = useOrganizationMock();
  const navigate = useNavigate();
  const existing = centres.find((item) => item.id === centreId);
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-5"><PageHeading title={existing ? `Edit ${existing.name}` : "Create multimodal centre"} description="Define the centre identity, readiness, facilities, and governance owner." /><form className="max-w-4xl rounded-lg border bg-card p-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name")); const id = existing?.id ?? name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); saveCentre({ id, name, location: String(form.get("location")), district: String(form.get("district")), status: String(form.get("status")) as Centre["status"], bays: Number(form.get("bays")), description: String(form.get("description")) }); navigate(`/admin/centres/${id}`); }}><div className="grid gap-4 sm:grid-cols-2"><Field name="name" label="Centre name" value={existing?.name} placeholder="Makumbura MMC" /><Field name="location" label="Location" value={existing?.location} placeholder="Kottawa" /><Field name="district" label="District" value={existing?.district} placeholder="Colombo" /><Field name="bays" label="Number of bays" value={String(existing?.bays ?? "")} placeholder="12" type="number" /><label className="grid gap-1.5 text-sm font-medium">Operational status<Select name="status" defaultValue={existing?.status ?? "Planned"}><SelectTrigger className="w-full bg-muted/60"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Planned">Planned</SelectItem><SelectItem value="Operating">Operating</SelectItem></SelectContent></Select></label><Field name="description" label="Description" value={existing?.description} placeholder="Connected modes and centre purpose" /></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => navigate(-1)}>Cancel</Button><Button type="submit">{existing ? "Save changes" : "Create centre"}</Button></div></form></main>;
}

function Field({ name, label, value, placeholder, type }: { name: string; label: string; value?: string; placeholder: string; type?: string }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<Input name={name} defaultValue={value} placeholder={placeholder} type={type} required /></label>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>; }
function Check({ label, complete }: { label: string; complete: boolean }) { return <div className="flex items-center justify-between rounded-md border p-3 text-sm"><span>{label}</span><StatusBadge label={complete ? "Complete" : "Required"} tone={complete ? "good" : "warning"} /></div>; }
function Summary({ icon: Icon, label, value, href }: { icon: typeof TrainFront; label: string; value: string; href: string }) { return <Link to={href} className="group rounded-lg border bg-card p-4 transition hover:border-primary/30 hover:shadow-sm"><div className="flex items-center justify-between"><Icon className="size-4 text-primary" /><ChevronRight className="size-4 text-muted-foreground transition group-hover:translate-x-0.5" /></div><p className="mt-3 text-sm text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></Link>; }
