import { useState } from "react";
import { ArrowLeft, Eye, EyeOff, LockKeyhole } from "lucide-react";
import { Link, useNavigate } from "react-router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiClient } from "@/lib/api/api-client";

export function PasswordChangePage() {
  const navigate = useNavigate();
  const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (next.length < 8) return setError("New password must be at least 8 characters."); if (next !== confirm) return setError("New passwords do not match."); setSaving(true); try { await apiClient("/api/v1/auth/change-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword: current, newPassword: next }) }); setSaved(true); setCurrent(""); setNext(""); setConfirm(""); } catch { setError("We could not update your password. Check your current password and try again."); } finally { setSaving(false); } }
  return <main className="min-h-screen bg-slate-50 px-5 py-10"><div className="mx-auto max-w-xl"><Link to="/profile" className="inline-flex items-center gap-2 text-sm font-medium text-primary"><ArrowLeft className="size-4" /> Back to profile</Link><section className="mt-7 rounded-2xl border border-slate-200 bg-white p-7 sm:p-9"><div className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><LockKeyhole className="size-5" /></div><h1 className="mt-5 text-2xl font-semibold tracking-tight">Change password</h1><p className="mt-2 text-sm leading-6 text-slate-500">Use a unique password with at least eight characters.</p>{saved ? <div className="mt-7 space-y-5"><p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">Your password has been updated successfully.</p><Button className="w-full rounded-full" onClick={() => navigate("/profile")}>Return to profile</Button></div> : <form onSubmit={submit} className="mt-7 space-y-5"><PasswordField id="current-password" label="Current password" value={current} onChange={setCurrent} show={show} toggle={() => setShow(!show)} /><PasswordField id="new-password" label="New password" value={next} onChange={setNext} show={show} toggle={() => setShow(!show)} /><PasswordField id="confirm-password" label="Confirm new password" value={confirm} onChange={setConfirm} show={show} toggle={() => setShow(!show)} />{error && <p className="text-sm text-red-600">{error}</p>}<Button type="submit" disabled={saving} className="h-11 w-full rounded-full">{saving ? "Updating..." : "Update password"}</Button></form>}</section></div></main>;
}
function PasswordField({ id, label, value, onChange, show, toggle }: { id: string; label: string; value: string; onChange: (value: string) => void; show: boolean; toggle: () => void }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><div className="relative"><Input id={id} type={show ? "text" : "password"} value={value} onChange={(event) => onChange(event.target.value)} className="h-11 rounded-xl bg-[#f5f5f7] pr-11" required /><button type="button" onClick={toggle} aria-label={show ? "Hide password" : "Show password"} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-slate-500">{show ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></div></div>; }
