import { useState } from "react";
import { Link, useSearchParams } from "react-router";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { apiClient } from "@/lib/api/api-client";

type Trip = { id: string; scheduledTime: string; status: string; route: string; routeName?: string; vehicle?: string };
type Seat = { seatNumber: string; isAvailable: boolean };

export function CheckoutPage() {
  const [params] = useSearchParams(); const routeId = params.get("routeId"); const passengers = Number(params.get("passengers") ?? 1); const [tripId, setTripId] = useState(""); const [seat, setSeat] = useState(""); const [error, setError] = useState(""); const [confirmed, setConfirmed] = useState(false);
  const trips = useQuery({ queryKey: ["booking-trips", routeId], enabled: Boolean(routeId), queryFn: () => apiClient<Trip[]>(`/api/v1/trips?routeId=${routeId}`) });
  const seats = useQuery({ queryKey: ["booking-seats", tripId], enabled: Boolean(tripId), queryFn: () => apiClient<Seat[]>(`/api/v1/bookings/trips/${tripId}/seats`) });
  async function confirm() { if (!tripId || !seat) return; setError(""); try { await apiClient("/api/v1/bookings/me", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tripId, seatNumber: seat }) }); setConfirmed(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to confirm booking"); } }
  return <main className="min-h-screen bg-slate-50 px-5 py-10"><section className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-8"><p className="text-sm font-medium text-primary">UPTSLK booking</p><h1 className="mt-2 text-2xl font-semibold">Confirm your journey</h1><p className="mt-2 text-sm text-slate-500">{passengers} passenger{passengers === 1 ? "" : "s"}. Choose a departure and seat.</p>{confirmed ? <div className="mt-8 rounded-xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-800"><p className="font-semibold">Booking confirmed</p><p className="mt-1 text-sm">Your seat {seat} has been reserved.</p></div> : <><div className="mt-7 space-y-3"><h2 className="font-semibold">Available departures</h2>{trips.isLoading && <p className="text-sm text-slate-500">Loading departures...</p>}{!trips.isLoading && trips.data?.length === 0 && <p className="text-sm text-slate-500">No departures are available for this route.</p>}{trips.data?.map((trip) => <button type="button" key={trip.id} onClick={() => { setTripId(trip.id); setSeat(""); }} className={`w-full rounded-xl border p-4 text-left ${tripId === trip.id ? "border-primary bg-primary/5" : "border-slate-200"}`}><span className="font-medium">{new Date(trip.scheduledTime).toLocaleString()}</span><span className="ml-3 text-sm text-slate-500">{trip.status}</span></button>)}</div>{tripId && <div className="mt-7"><h2 className="font-semibold">Select a seat</h2><div className="mt-3 grid grid-cols-5 gap-2">{seats.data?.map((item) => <button type="button" key={item.seatNumber} disabled={!item.isAvailable} onClick={() => setSeat(item.seatNumber)} className={`rounded-lg border px-2 py-2 text-sm ${!item.isAvailable ? "cursor-not-allowed bg-slate-100 text-slate-400" : seat === item.seatNumber ? "border-primary bg-primary text-white" : "border-slate-200"}`}>{item.seatNumber}</button>)}</div></div>}{error && <p className="mt-5 text-sm text-red-600">{error}</p>}<Button className="mt-7 w-full rounded-full bg-primary" disabled={!tripId || !seat} onClick={confirm}>Confirm booking</Button></>}<Button render={<Link to="/" />} variant="link" className="mt-3 w-full">Back to search</Button></section></main>;
}
