import { useState, type FormEvent } from "react";
import { Check, KeyRound, LockKeyhole, ShieldCheck, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageHeading } from "@/components/shared/PageHeading";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { accessRequests, platformRoles, type PlatformRole } from "@/mock/organization";

export function RolesPage() {
  const [roles, setRoles] = useState(platformRoles);
  const [showForm, setShowForm] = useState(false);
  function addRole(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const permissions = String(form.get("permissions")).split(",").map((item) => item.trim()).filter(Boolean); const role: PlatformRole = { id: `ROLE-${String(roles.length + 1).padStart(2, "0")}`, name: String(form.get("name")), scope: String(form.get("scope")) as PlatformRole["scope"], users: 0, permissions }; setRoles((current) => [...current, role]); setShowForm(false); }
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-5"><PageHeading title="Roles & permissions" description="Review what each organization or centre-scoped role can access." action={<Button onClick={() => setShowForm((value) => !value)}><KeyRound /> Create role</Button>} />{showForm && <form onSubmit={addRole} className="rounded-lg border bg-card p-5"><h2 className="font-semibold">Create custom role</h2><div className="mt-4 grid gap-4 md:grid-cols-[1fr_180px_1.5fr]"><label className="grid gap-1.5 text-sm font-medium">Role name<Input name="name" placeholder="Terminal supervisor" required /></label><label className="grid gap-1.5 text-sm font-medium">Scope<Select name="scope" defaultValue="Centre"><SelectTrigger className="w-full bg-muted/60"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Centre">Centre</SelectItem><SelectItem value="Global">Global</SelectItem></SelectContent></Select></label><label className="grid gap-1.5 text-sm font-medium">Permissions<Input name="permissions" placeholder="Dispatch, Bays, Incidents" required /></label></div><div className="mt-4 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setShowForm(false)}>Cancel</Button><Button type="submit">Create role</Button></div></form>}<div className="grid gap-4 xl:grid-cols-2">{roles.map((role) => <article key={role.id} className="rounded-lg border bg-card p-5"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-md bg-primary/10 text-primary"><ShieldCheck className="size-5" /></div><div><h2 className="font-semibold">{role.name}</h2><p className="text-sm text-muted-foreground">{role.users} assigned employees</p></div></div><StatusBadge label={`${role.scope} scope`} tone={role.scope === "Global" ? "warning" : "neutral"} /></div><div className="mt-5 flex flex-wrap gap-2">{role.permissions.map((permission) => <span key={permission} className="rounded-md border bg-muted/40 px-2.5 py-1 text-xs">{permission}</span>)}</div><div className="mt-5 flex justify-end"><Button size="sm" variant="outline">Review permissions</Button></div></article>)}</div><section className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><div className="flex gap-3"><LockKeyhole className="mt-0.5 size-4 shrink-0" /><p><strong>Least-privilege rule:</strong> centre roles only apply inside the employee’s assigned centre. Global access should remain limited to Super Admins.</p></div></section></main>;
}

export function AccessRequestsPage() {
  const [decisions, setDecisions] = useState<Record<string, "Approved" | "Rejected">>({});
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-5"><PageHeading title="Access requests" description="Approve exceptional access without changing an employee’s permanent role." /><section className="overflow-hidden rounded-lg border bg-card"><div className="hidden grid-cols-[minmax(220px,1fr)_minmax(220px,1fr)_160px_120px_190px] gap-4 border-b px-4 py-3 text-xs font-medium uppercase text-muted-foreground md:grid"><span>Employee</span><span>Requested access</span><span>Centre</span><span>Risk</span><span>Decision</span></div>{accessRequests.map((request) => <div key={request.id} className="grid gap-3 border-b px-4 py-4 md:grid-cols-[minmax(220px,1fr)_minmax(220px,1fr)_160px_120px_190px] md:items-center"><div><p className="font-medium">{request.employee}</p><p className="text-sm text-muted-foreground">{request.id} · {request.requested}</p></div><p className="text-sm">{request.request}</p><p className="text-sm text-muted-foreground">{request.centre}</p><StatusBadge label={request.risk} tone={request.risk === "Elevated" ? "warning" : "neutral"} />{decisions[request.id] ? <StatusBadge label={decisions[request.id]} tone={decisions[request.id] === "Approved" ? "good" : "danger"} /> : <div className="flex gap-2"><Button size="sm" onClick={() => setDecisions((value) => ({ ...value, [request.id]: "Approved" }))}><Check /> Approve</Button><Button size="sm" variant="outline" onClick={() => setDecisions((value) => ({ ...value, [request.id]: "Rejected" }))}><X /> Reject</Button></div>}</div>)}</section></main>;
}
