import { Activity, Building2, ChevronRight, ShieldAlert, UserPlus, UsersRound } from "lucide-react";
import { Link } from "react-router";
import { Button } from "@/components/ui/button";
import { PageHeading } from "@/components/shared/PageHeading";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { useOrganizationMock } from "@/context/OrganizationMockContext";
import { accessRequests, auditEvents } from "@/mock/organization";

export function SuperAdminOverviewPage() {
  const { centres, employees } = useOrganizationMock();
  const operating = centres.filter((item) => item.status === "Operating");
  const activeEmployees = employees.filter((item) => item.status === "Active");
  return <main className="flex flex-1 flex-col gap-5 bg-muted/20 p-5"><PageHeading title="Organization overview" description="Govern centres, people, access, and platform health across UPTSLK." action={<div className="flex gap-2"><Button variant="outline" render={<Link to="/admin/employees?create=true" />}><UserPlus /> Add employee</Button><Button render={<Link to="/admin/centres/new" />}><Building2 /> Create centre</Button></div>} /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Building2} label="Operating centres" value={String(operating.length)} detail={`${centres.length - operating.length} planned`} /><Metric icon={UsersRound} label="UPTSLK employees" value={String(employees.length)} detail={`${activeEmployees.length} active`} /><Metric icon={ShieldAlert} label="Access requests" value={String(accessRequests.length)} detail="Require review" /><Metric icon={Activity} label="Platform health" value="4/5" detail="1 degraded service" /></section><section className="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_380px]"><article className="overflow-hidden rounded-lg border bg-card"><div className="flex items-center justify-between border-b px-4 py-3"><div><h2 className="font-semibold">Centre portfolio</h2><p className="text-sm text-muted-foreground">Governance status and accountable management</p></div><Button size="sm" variant="outline" render={<Link to="/admin/centres" />}>View all</Button></div><div className="divide-y">{centres.map((centre) => { const manager = employees.find((employee) => employee.centreId === centre.id && employee.role === "Centre Manager"); return <Link key={centre.id} to={`/admin/centres/${centre.id}`} className="grid gap-3 px-4 py-3 hover:bg-muted/40 sm:grid-cols-[minmax(0,1fr)_150px_120px_24px] sm:items-center"><div><p className="font-medium">{centre.name}</p><p className="text-sm text-muted-foreground">{centre.location} · {centre.bays} bays</p></div><p className="text-sm text-muted-foreground">{manager?.name ?? "Manager unassigned"}</p><StatusBadge label={centre.status} tone={centre.status === "Operating" ? "good" : "neutral"} /><ChevronRight className="size-4 text-muted-foreground" /></Link>; })}</div></article><article className="overflow-hidden rounded-lg border bg-card"><div className="border-b px-4 py-3"><h2 className="font-semibold">Recent administration</h2><p className="text-sm text-muted-foreground">Organization-wide audit activity</p></div><div className="divide-y">{auditEvents.slice(0, 4).map((event) => <div key={event.id} className="p-4"><p className="text-sm"><span className="font-medium">{event.actor}</span> {event.action.toLowerCase()}</p><p className="mt-1 text-xs text-muted-foreground">{event.target} · {event.time}</p></div>)}</div></article></section></main>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Activity; label: string; value: string; detail: string }) {
  return <article className="rounded-lg border bg-card p-4"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><Icon className="size-4 text-primary" /></div><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></article>;
}
