import { useState } from "react";
import { CalendarClock, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeading } from "@/components/shared/PageHeading";
import { RouteServiceStatus } from "@/features/centres/components/RouteServiceStatus";
import { useAuth } from "@/hooks/useAuth";
import { centreRouteServices, type CentreRouteService } from "@/mock/centre-services";
import { useDispatchMock } from "@/context/DispatchMockContext";
import { dispatchResources, type Trip } from "@/mock/dispatch";

export function TimetablesPage() {
  const { user } = useAuth();
  const { saveTrip } = useDispatchMock();
  const [query, setQuery] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [notice, setNotice] = useState("");
  const [patterns, setPatterns] = useState(() => centreRouteServices.filter((item) => item.centreId === user?.centreId));
  const services = patterns.filter((item) => `${item.route} ${item.origin} ${item.destination}`.toLowerCase().includes(query.toLowerCase()));
  function addMinutes(time: string, minutes: number) { const [hours, mins] = time.split(":").map(Number); const date = new Date(2000, 0, 1, hours, mins + minutes); return `${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`; }
  function generateTrips() { const centreId = user?.centreId ?? "makumbura"; const resources = dispatchResources[centreId as keyof typeof dispatchResources] ?? dispatchResources.makumbura; let generated = 0; try { patterns.forEach((pattern) => pattern.runs.forEach((run, index) => { const trip: Trip = { id: `TRP-G${Date.now().toString().slice(-3)}${generated}`, centreId, serviceDate: "2026-09-08", scheduledTime: run.time, route: pattern.route, origin: pattern.origin, destination: pattern.destination, vehicleId: resources.vehicles[index % resources.vehicles.length], driverId: resources.drivers[index % resources.drivers.length], bay: pattern.bay, occupancy: 0, status: "Scheduled", notes: `Generated from ${pattern.id}`, updatedAt: "Generated just now" }; saveTrip(trip); generated += 1; })); setNotice(`${generated} trips generated for Sep 8 and added to dispatch.`); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Could not generate trips."); } }
  return <main className="flex flex-1 flex-col gap-4 bg-muted/20 p-4"><PageHeading title="Timetables" description="Manage recurring departures, headways, assigned bays, and operating vehicles." action={<div className="flex gap-2"><Button variant="outline" onClick={generateTrips}>Generate next-day trips</Button><Button onClick={() => setShowForm((value) => !value)}><Plus /> Add service pattern</Button></div>} />{notice && <div className="rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-sm">{notice}</div>}{showForm && <form className="rounded-lg border bg-card p-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const first = String(form.get("first")); const interval = Number(form.get("interval")); const route = String(form.get("route")); const pattern: CentreRouteService = { id: `SVC-${Date.now()}`, centreId: user?.centreId ?? "makumbura", route, origin: "Centre terminal", destination: String(form.get("destination")), intervalMinutes: interval, bay: String(form.get("bay")), currentLocation: "Not started", runs: [0, 1, 2, 3].map((index) => ({ time: addMinutes(first, interval * index), vehicle: index === 0 ? String(form.get("vehicle")) : "Assignment pending", state: index === 0 ? "Boarding" as const : "Scheduled" as const, detail: index === 0 ? `Bay ${String(form.get("bay"))} · Boarding` : "Awaiting vehicle assignment" })) }; setPatterns((current) => [...current, pattern]); setShowForm(false); }}><h2 className="font-semibold">New recurring service</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-6"><Input name="route" placeholder="Route number" required /><Input name="destination" placeholder="Destination" required /><Input name="first" type="time" required /><Input name="interval" placeholder="Headway minutes" type="number" required /><Input name="bay" placeholder="Assigned bay" required /><Input name="vehicle" placeholder="First vehicle" required /></div><div className="mt-4 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setShowForm(false)}>Cancel</Button><Button type="submit">Save pattern</Button></div></form>}<div className="relative max-w-md"><CalendarClock className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search route or destination" value={query} onChange={(event) => setQuery(event.target.value)} /></div>{services.map((service) => <RouteServiceStatus key={service.id} service={service} />)}{services.length === 0 && <div className="rounded-lg border border-dashed bg-card p-10 text-center text-sm text-muted-foreground">No service patterns match this search.</div>}</main>;
}
